# Generated by Django 5.1.1 on 2024-10-04 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_remove_task_user_alter_task_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
